name: Reveal Secrets

on:
  workflow_dispatch: # 手动触发

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_KEY: ${{ secrets.SFTP_KEY }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_TARGET_DIR: ${{ secrets.SFTP_TARGET_DIR }}
          API_URL: ${{ secrets.API_URL }}
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
          QQ_EMAIL_PASSWORD: ${{ secrets.QQ_EMAIL_PASSWORD }}
        run: |
          echo "请复制下方各行对应的 Base64 字符串并在本地解码"
          echo "------------------------------------------------"
          
          echo -n "SIGNING_KEY_STORE_PATH: " && echo -n "$SIGNING_KEY_STORE_PATH" | base64
          echo -n "KEYSTORE_BASE64: " && echo -n "$KEYSTORE_BASE64" | base64
          echo -n "KEY_ALIAS: " && echo -n "$KEY_ALIAS" | base64
          echo -n "KEY_PASSWORD: " && echo -n "$KEY_PASSWORD" | base64
          echo -n "KEYSTORE_PASSWORD: " && echo -n "$KEYSTORE_PASSWORD" | base64
          echo -n "SFTP_HOST: " && echo -n "$SFTP_HOST" | base64
          echo -n "SFTP_USER: " && echo -n "$SFTP_USER" | base64
          echo -n "SFTP_KEY: " && echo -n "$SFTP_KEY" | base64
          echo -n "SFTP_PORT: " && echo -n "$SFTP_PORT" | base64
          echo -n "SFTP_TARGET_DIR: " && echo -n "$SFTP_TARGET_DIR" | base64
          echo -n "API_URL: " && echo -n "$API_URL" | base64
          echo -n "QQ_EMAIL: " && echo -n "$QQ_EMAIL" | base64
          echo -n "QQ_EMAIL_PASSWORD: " && echo -n "$QQ_EMAIL_PASSWORD" | base64
