name: Reveal Secrets

on:
  workflow_dispatch: # 手动触发

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret
        env:
          # 在这里列出你所有想找回的秘密
          MY_SECRET_CONTENT: ${{ secrets.YOUR_SECRET_NAME }} 
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }} 
          KEYSTORE_BASE64 : ${{ secrets.KEYSTORE_BASE64  }} 
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }} 
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }} 
          KEYSTORE_PASSWORD : ${{ secrets.KEYSTORE_PASSWORD  }} 
          SFTP_HOST: ${{ secrets.SFTP_HOST }} 
          SFTP_USER: ${{ secrets.SFTP_USER }} 
          SFTP_KEY: ${{ secrets.SFTP_KEY }} 
          SFTP_PORT: ${{ secrets.SFTP_PORT }} 
          SFTP_TARGET_DIR: ${{ secrets.SFTP_TARGET_DIR }} 
          API_URL: ${{ secrets.API_URL }} 
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }} 
          QQ_EMAIL_PASSWORD: ${{ secrets.QQ_EMAIL_PASSWORD }} 
          
        run: |
          # 将秘密进行 Base64 编码后输出，防止被 GitHub 日志过滤器屏蔽
          echo "The base64 encoded secret is:"
          echo $MY_SECRET_CONTENT | base64
          echo $SIGNING_KEY_STORE_PATH | base64
          echo $KEYSTORE_BASE64  | base64
          echo $KEY_ALIAS | base64
          echo $KEY_PASSWORD | base64
          echo $KEYSTORE_PASSWORD  | base64
          echo $SFTP_HOST | base64
          echo $SFTP_USER | base64
          echo $SFTP_KEY | base64
          echo $SFTP_PORT | base64
          echo $SFTP_TARGET_DIR | base64
          echo $API_URL | base64
          echo $QQ_EMAIL | base64
          echo $QQ_EMAIL_PASSWORD | base64
